#cloud-config

---
write-files:
  - path: /etc/conf.d/nfs
    permissions: '0644'
    content: |
      OPTS_RPC_MOUNTD=""
  - path: /opt/bin/wupiao
    permissions: '0755'
    content: |
      #!/bin/bash
      # [w]ait [u]ntil [p]ort [i]s [a]ctually [o]pen
      [ -n "$1" ] && \
        until curl -o /dev/null -sIf http://${1}; do \
          sleep 1 && echo .;
        done;
      exit $?
  - path: /etc/hosts
    permissions: '0755'
    content: |
      127.0.0.1 localhost
      <static-ip> localregistry

coreos:
  etcd2:
    name: __NAME__
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    advertise-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    initial-cluster: __ETCD_SEED_CLUSTER__
    proxy: on
  fleet:
    public-ip: $public_ipv4
    metadata: "role=minion"
  flannel:
    interface: $public_ipv4
  units:
    - name: rpcbind.service
      enable: true
      command: start
    - name: rpc-statd.service
      enable: true
      command: start
    - name: flanneld.service
      command: start
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Unit]
            Requires=etcd2.service
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"10.244.0.0/16", "Backend": {"Type": "host-gw"}}'
    - name: fleet.service
      command: start
    - name: docker.service
      command: start
      drop-ins:
        - __PROXY_LINE__name: http-proxy.conf
          __PROXY_LINE__content: |
          __PROXY_LINE__[Service]
          __PROXY_LINE__EnvironmentFile=/etc/environment
      drop-ins:
        - name: 50-docker-options.conf
          content: |
            [Service]
            Environment='DOCKER_OPTS=--debug -H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock --insecure-registry localregistry:5000'
    - name: early-docker.service
      drop-ins:
        - __PROXY_LINE__name: http-proxy.conf
          __PROXY_LINE__content: |
            __PROXY_LINE__[Service]
            __PROXY_LINE__EnvironmentFile=/etc/environment
    - name: kube-proxy.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Proxy
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Requires=network-online.target
        After=network-online.target
        [Service]
        ExecStartPre=/opt/bin/wupiao __MASTER_IP__:8080
        ExecStart=/opt/bin/kube-proxy \
          --master=__MASTER_IP__:8080 \
          --logtostderr=true
        Restart=always
        RestartSec=10
    - name: kube-kubelet.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Kubelet
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Requires=network-online.target
        After=network-online.target
        [Service]
        ExecStartPre=/usr/bin/mkdir -p /opt/kubernetes/manifests/
        ExecStartPre=/opt/bin/wupiao __MASTER_IP__:8080
        ExecStart=/opt/bin/kubelet \
          --address=0.0.0.0 \
          --port=10250 \
          --hostname_override=$public_ipv4 \
          --api_servers=__MASTER_IP__:8080 \
          --cloud_provider=__CLOUDPROVIDER__ \
          --allow_privileged=true \
          --cluster_dns=10.100.0.10 \
          --cluster_domain=__DNS_DOMAIN__ \
          --logtostderr=true \
          --config=/opt/kubernetes/manifests/ \
          --cadvisor_port=4194 \
          --healthz_bind_address=0.0.0.0 \
          --healthz_port=10248
        Restart=always
        RestartSec=10
        WorkingDirectory=/root/
  update:
    group: __CHANNEL__
    reboot-strategy: off
